import type { Tool } from "./types";

const V = "2026-08-20";

export const SEED_TOOLS: Tool[] = [
  {
    id: "vlr-gg",
    name: "VLR.gg",
    slug: "vlr-gg",
    shortDescription:
      "The standard for Valorant esports data, schedules, and match stats.",
    description:
      "VLR.gg is the community’s primary esports hub: VCT and regional events, live scores, detailed match pages, player and team profiles, and round-by-round stats. Use it for the pro scene — not for ranked solo-queue lookups.",
    websiteUrl: "https://www.vlr.gg",
    category: "Esports & Competitive",
    tags: ["esports", "vct", "schedules", "pro-stats"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Match schedules and live scores",
      "Player, team, and event pages",
      "Round-by-round series breakdowns",
      "Regional and international coverage",
    ],
    featured: true,
  },
  {
    id: "tracker-gg",
    name: "Tracker.gg",
    slug: "tracker-gg",
    shortDescription:
      "Deep player profiles, leaderboards, and a desktop overlay.",
    description:
      "Tracker.gg is one of the largest public Valorant stat sources. Web profiles cover rank, K/D, match history, and agent/map splits. The Overwolf desktop app adds live overlay insights. Some deeper history sits behind a paid tier.",
    websiteUrl: "https://tracker.gg/valorant",
    category: "Trackers & Stats",
    tags: ["stats", "leaderboards", "overlay", "match-history"],
    platforms: ["web", "overwolf", "desktop"],
    pricing: "freemium",
    status: "active",
    lastVerified: V,
    features: [
      "Public player profiles",
      "Global and regional leaderboards",
      "Agent and map performance",
      "Optional desktop overlay",
    ],
    safetyNotes:
      "Desktop overlay runs through Overwolf. Free web lookup does not require a download.",
    featured: true,
    spotlight: "editors",
  },
  {
    id: "blitz-gg",
    name: "Blitz.gg",
    slug: "blitz-gg",
    shortDescription:
      "Desktop overlay with live scouting, lineups, and post-match analysis.",
    description:
      "Blitz is overlay-first: opponent intel in agent select, combat overlays, agent guides, and lineup maps. The web tracker exists, but the product is built around the desktop client.",
    websiteUrl: "https://blitz.gg/valorant",
    category: "Overlays & Desktop Apps",
    tags: ["overlay", "lineups", "guides", "live-scouting"],
    platforms: ["desktop", "overwolf"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Live opponent scouting",
      "In-game overlay",
      "Agent guides and lineup maps",
      "Post-match analysis",
    ],
    safetyNotes: "Requires a desktop client. Keep it updated and avoid unofficial forks.",
    featured: true,
  },
  {
    id: "instalock",
    name: "Instalock",
    slug: "instalock",
    shortDescription:
      "No-install web companion with live opponent intel and a store checker.",
    description:
      "Instalock is browser-only: opponent ranks and recent form in agent select (including some incognito cases), career stats, and store checking without a heavy overlay. Positioned as an ad-light alternative to desktop trackers.",
    websiteUrl: "https://www.instalock.net",
    category: "Trackers & Stats",
    tags: ["web-only", "no-install", "incognito", "store-checker"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-22",
    features: [
      "Live opponent intel in agent select",
      "Store checker without the Riot Client",
      "Lightweight browser experience",
      "Career stats",
    ],
    safetyNotes:
      "Uses Riot authentication. Review their privacy policy before signing in.",
    featured: true,
  },
  {
    id: "patchline",
    name: "PATCHLINE",
    slug: "patchline",
    shortDescription:
      "Every agent buff and nerf, patch by patch, at a glance.",
    description:
      "PATCHLINE tracks Valorant balance changes over time rather than burying them in patch notes: agent buffs and nerfs laid out patch by patch, filterable by role, alongside map rotation changes and a ranking of which agents Riot has touched most. Each entry links back to the official Riot notes.",
    websiteUrl: "https://valopatchline.com",
    category: "Other",
    tags: ["patch-notes", "balance", "meta", "agents"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Agent balance history, patch by patch",
      "Buffs and nerfs filtered by role",
      "Map rotation changes",
      "Ranking of the most-patched agents",
      "Links through to official Riot patch notes",
    ],
    featured: true,
    spotlight: "weekly",
  },
  {
    id: "vcrdb",
    name: "VCRDB",
    slug: "vcrdb",
    shortDescription:
      "Crosshair database, live builder, LFG, and sensitivity tools.",
    description:
      "VCRDB is a community crosshair hub: browse pro and player codes, build with a live preview, convert sensitivity, and use extra player tools from the same team.",
    websiteUrl: "https://www.vcrdb.net",
    category: "Crosshairs & Settings",
    tags: ["crosshair", "builder", "pro-settings", "sens-converter"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Pro and community crosshair codes",
      "Live crosshair builder",
      "Sensitivity converter",
      "Community tools",
    ],
    featured: true,
    spotlight: "gem",
  },
  {
    id: "u-gg",
    name: "U.GG",
    slug: "u-gg",
    shortDescription:
      "Tier lists, peek maps, profiles, and a desktop companion.",
    description:
      "U.GG covers Valorant with data-driven peek maps, agent/weapon tier lists, player profiles, and a desktop app for live scouting and in-game stats.",
    websiteUrl: "https://u.gg/val",
    category: "Trackers & Stats",
    tags: ["tier-list", "peek-maps", "profiles", "overlay"],
    platforms: ["web", "desktop"],
    pricing: "freemium",
    status: "active",
    lastVerified: V,
    features: [
      "Daily peek maps",
      "Agent and weapon tier lists",
      "Player profiles",
      "Desktop live insights",
    ],
    featured: false,
  },
  {
    id: "op-gg",
    name: "OP.GG",
    slug: "op-gg",
    shortDescription:
      "Player lookup and companion overlay from the OP.GG network.",
    description:
      "OP.GG’s Valorant tracker offers ranked lookup, match history, and a desktop overlay alongside their League products. A familiar option if you already use OP.GG for other Riot games.",
    websiteUrl: "https://valorant.op.gg",
    category: "Trackers & Stats",
    tags: ["stats", "lookup", "overlay"],
    platforms: ["web", "desktop"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Riot ID search",
      "Match history",
      "Desktop overlay",
    ],
    featured: false,
  },
  {
    id: "dak-gg",
    name: "Dak.gg",
    slug: "dak-gg",
    shortDescription: "Regional tracker with profiles and competitive stats.",
    description:
      "Dak.gg provides Valorant player search, ranked stats, and match history. Popular in some APAC communities as an alternative to Tracker.gg.",
    websiteUrl: "https://dak.gg/valorant",
    category: "Trackers & Stats",
    tags: ["stats", "lookup", "apac"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: ["Player profiles", "Ranked stats", "Match history"],
    featured: false,
  },
  {
    id: "mobalytics",
    name: "Mobalytics",
    slug: "mobalytics",
    shortDescription:
      "Companion with overlays, agent guides, and performance insights.",
    description:
      "Mobalytics mixes overlays with coaching-style agent guides — ability usage, map tips, and performance tracking. Desktop-first via Overwolf.",
    websiteUrl: "https://mobalytics.gg/valorant",
    category: "Overlays & Desktop Apps",
    tags: ["overlay", "guides", "coaching"],
    platforms: ["desktop", "overwolf", "web"],
    pricing: "freemium",
    status: "active",
    lastVerified: V,
    features: [
      "In-game overlays",
      "Agent ability guides",
      "Performance tracking",
    ],
    safetyNotes: "Desktop client / Overwolf based.",
    featured: false,
  },
  {
    id: "lineupsvalorant",
    name: "LineupsValorant",
    slug: "lineupsvalorant",
    shortDescription:
      "Searchable lineup library filtered by map, agent, and ability.",
    description:
      "LineupsValorant collects community lineups with filters for map, agent, ability, side, and type. Fast lookup for Sova, Fade, Viper, and other utility agents.",
    websiteUrl: "https://lineupsvalorant.com",
    category: "Lineups & Strategies",
    tags: ["lineups", "utility", "maps"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Filter by map, agent, ability",
      "Attack and defense lineups",
      "Visual lineup guides",
    ],
    featured: false,
  },
  {
    id: "liquipedia",
    name: "Liquipedia",
    slug: "liquipedia",
    shortDescription:
      "Wiki-style coverage of teams, players, and tournaments.",
    description:
      "Liquipedia’s Valorant wiki is the long-form record of the competitive scene: rosters, transfer history, tournament pages, and prize pools. Complements VLR.gg rather than replacing it.",
    websiteUrl: "https://liquipedia.net/valorant/",
    category: "Esports & Competitive",
    tags: ["wiki", "rosters", "tournaments"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Team and player pages",
      "Tournament history",
      "Transfer tracking",
    ],
    featured: false,
  },
  {
    id: "rib-gg",
    name: "Rib.gg",
    slug: "rib-gg",
    shortDescription: "Advanced Valorant esports analytics and VOD-oriented stats.",
    description:
      "Rib.gg focuses on deeper competitive analytics — agent comps, player trends, and series-level data used by analysts following VCT.",
    websiteUrl: "https://www.rib.gg",
    category: "Esports & Competitive",
    tags: ["analytics", "vct", "comps"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Competitive analytics",
      "Agent composition data",
      "Player and team trends",
    ],
    featured: false,
  },
  {
    id: "prosettings",
    name: "ProSettings",
    slug: "prosettings",
    shortDescription: "Pro player hardware, sensitivity, and crosshair settings.",
    description:
      "ProSettings tracks VCT players’ mice, DPI, in-game sens, crosshairs, and gear. Useful when copying a setup — always verify against a recent source.",
    websiteUrl: "https://prosettings.net/games/valorant/",
    category: "Crosshairs & Settings",
    tags: ["pro-settings", "hardware", "sensitivity"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Per-player settings pages",
      "Crosshair and sensitivity",
      "Gear lists",
    ],
    featured: false,
  },
  {
    id: "valoguide",
    name: "ValoGuide",
    slug: "valoguide",
    shortDescription:
      "Inventory builder, crosshairs, leaks, and marketplace safety notes.",
    description:
      "ValoGuide is a community hub: shareable inventories without Riot login, pro crosshair codes, leak tracking, and a curated list of account marketplaces with safety context.",
    websiteUrl: "https://valoguide.com",
    category: "Other",
    tags: ["inventory", "crosshairs", "leaks", "marketplaces"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Public inventory pages",
      "Crosshair codes",
      "Leaks feed",
      "Marketplace safety guides",
    ],
    featured: false,
  },
  {
    id: "valodex",
    name: "ValoDex",
    slug: "valodex",
    shortDescription:
      "Store, inventory, multi-account tracker, and shareable cards.",
    description:
      "ValoDex wraps store rotation, inventory value, rank overview, and match breakdowns behind a Riot login. Paid tiers unlock more accounts.",
    websiteUrl: "https://valodex.net",
    category: "Store, Inventory & Skins",
    tags: ["store", "inventory", "multi-account"],
    platforms: ["web"],
    pricing: "freemium",
    status: "active",
    lastVerified: V,
    features: [
      "Daily store and night market",
      "Inventory and collection value",
      "Multi-account switching",
      "Shareable account cards",
    ],
    safetyNotes:
      "Requires Riot sign-in. Prefer official OAuth; never enter your password on unknown clones.",
    featured: false,
  },
  {
    id: "valocheck",
    name: "ValoCheck",
    slug: "valocheck",
    shortDescription: "Lightweight free stats lookup with leaderboards.",
    description:
      "ValoCheck is a fast, no-signup stats site: Riot ID search, K/D, ACS, agent splits, and regional leaderboards. Data via community APIs.",
    websiteUrl: "https://valocheck.com",
    category: "Trackers & Stats",
    tags: ["stats", "no-signup", "leaderboards"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Instant Riot ID search",
      "Match history",
      "Regional leaderboards",
    ],
    featured: false,
  },
  {
    id: "valking",
    name: "Valking.gg",
    slug: "valking",
    shortDescription:
      "Free web tracker with live meta, leaderboards, and Discord bot.",
    description:
      "Valking.gg is a browser tracker with rank/match stats, an agent meta tier list, map win rates, and a Discord bot for rank roles and patch notes.",
    websiteUrl: "https://valking.gg/en",
    category: "Trackers & Stats",
    tags: ["stats", "meta", "discord"],
    platforms: ["web", "discord", "mobile"],
    pricing: "freemium",
    status: "active",
    lastVerified: V,
    features: [
      "Player lookup",
      "Agent meta tier list",
      "Discord rank roles",
      "Patch notes",
    ],
    featured: false,
  },
  {
    id: "strats-gg",
    name: "Strats.gg",
    slug: "strats-gg",
    shortDescription:
      "Stats plus in-game lineup tool and community-submitted lineups.",
    description:
      "Strats.gg combines tracking with a lineup tool and crosshair builder. Players can submit lineups; a desktop overlay is available.",
    websiteUrl: "https://strats.gg",
    category: "Lineups & Strategies",
    tags: ["lineups", "overlay", "crosshair"],
    platforms: ["web", "overwolf", "desktop"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Lineup tool",
      "Community submissions",
      "Crosshair builder",
      "Optional overlay",
    ],
    featured: false,
  },
  {
    id: "valoranthub",
    name: "Valorant Hub",
    slug: "valorant-hub",
    shortDescription:
      "Database wiki for agents, weapons, skins, maps, and news.",
    description:
      "Valorant Hub is a reference wiki: agents, weapon skins, maps, seasons, and news. Better as a catalog than as a live tracker.",
    websiteUrl: "https://valoranthub.com",
    category: "Other",
    tags: ["wiki", "skins", "agents", "maps"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Agent and weapon pages",
      "Skin collections",
      "Map overviews",
      "News feed",
    ],
    featured: false,
  },
  {
    id: "vstats",
    name: "vstats.gg",
    slug: "vstats",
    shortDescription:
      "Companion for agent/weapon stats, comps, and tactical spots.",
    description:
      "vstats.gg is a Valorant companion covering agent and weapon stats, team comps, ranks, and tactical spots. Available as an Overwolf app.",
    websiteUrl: "https://vstats.gg",
    category: "Overlays & Desktop Apps",
    tags: ["stats", "comps", "overlay"],
    platforms: ["overwolf", "desktop", "web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Agent and weapon stats",
      "Team comps",
      "Tactical spots",
    ],
    featured: false,
  },
  {
    id: "aiming-pro",
    name: "Aiming.pro",
    slug: "aiming-pro",
    shortDescription: "Mouse sensitivity converter across games including Valorant.",
    description:
      "Aiming.pro is a sensitivity calculator: convert DPI and in-game sens between Valorant and other shooters so muscle memory stays consistent.",
    websiteUrl: "https://aiming.pro/mouse-sensitivity-calculator",
    category: "Crosshairs & Settings",
    tags: ["sensitivity", "converter", "aim"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Cross-game sensitivity conversion",
      "DPI and eDPI helpers",
    ],
    featured: false,
  },
  {
    id: "overwolf-store",
    name: "Overwolf Valorant apps",
    slug: "overwolf-valorant",
    shortDescription:
      "Official Overwolf catalog of Valorant overlays and companions.",
    description:
      "Not a single tool — Overwolf’s Valorant app store lists Tracker, Mobalytics, ValoPlant, ValoHunt, vstats, and other desktop overlays in one place. Useful when you specifically want an overlay.",
    websiteUrl: "https://www.overwolf.com/browse-by-game/valorant",
    category: "Overlays & Desktop Apps",
    tags: ["overlay", "catalog", "overwolf"],
    platforms: ["overwolf", "desktop"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Browse Overwolf Valorant apps",
      "Install overlays from one client",
    ],
    safetyNotes:
      "Only install from the official Overwolf catalog. Overlays sit beside Vanguard — stick to known publishers.",
    featured: false,
  },
  {
    id: "pley-store",
    name: "Pley Discord bot",
    slug: "pley-discord",
    shortDescription:
      "Discord bot for shop checks, agents, bundles, and esports info.",
    description:
      "Pley recommends their Discord bot as a lower-risk way to peek the daily shop versus random mobile APKs. Also covers agents, battle pass, maps, and esports commands.",
    websiteUrl: "https://pley.gg/valorant/valorant-store-tracker/",
    category: "Discord Bots & Utilities",
    tags: ["store", "discord", "shop"],
    platforms: ["discord", "web"],
    pricing: "free",
    status: "active",
    lastVerified: V,
    features: [
      "Shop commands in Discord",
      "Agent and map info",
      "Esports commands",
    ],
    safetyNotes:
      "Prefer open, well-known bots. Never paste your Riot password into Discord or a random APK.",
    featured: false,
  },
  {
    id: "thespike",
    name: "THESPIKE.GG",
    slug: "thespike",
    shortDescription:
      "Valorant esports news, interviews, and event coverage.",
    description:
      "THESPIKE.GG is a news-first competitive hub: match coverage, roster moves, interviews, and event pages. Complements VLR.gg if you want reporting around the scores rather than the scores themselves.",
    websiteUrl: "https://www.thespike.gg/",
    category: "Esports & Competitive",
    tags: ["news", "vct", "interviews", "coverage"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Daily competitive news",
      "Event hubs and match coverage",
      "Interviews and roster reporting",
    ],
    featured: true,
  },
  {
    id: "valorant-esports",
    name: "VALORANT Esports",
    slug: "valorant-esports",
    shortDescription:
      "Official VCT schedules, standings, and championship news.",
    description:
      "Riot’s official esports site for VCT, Game Changers, and international events. Use it for canonical schedules and format notes; pair with VLR.gg for deeper match stats.",
    websiteUrl: "https://valorantesports.com/",
    category: "Esports & Competitive",
    tags: ["official", "vct", "schedules", "riot"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Official VCT calendar",
      "Regional and international events",
      "Championship news",
    ],
    featured: false,
  },
  {
    id: "valorant-wiki",
    name: "VALORANT Wiki",
    slug: "valorant-wiki",
    shortDescription:
      "Official wiki for agents, maps, skins, patches, and lore.",
    description:
      "The official VALORANT wiki covers agents, weapons, maps, cosmetics, battle pass, store rotations, and patch notes. Player-written, hosted as Riot’s canonical wiki. Best first stop for “what does this do?” rather than live ranked stats.",
    websiteUrl: "https://wiki.playvalorant.com/en-us/",
    category: "Other",
    tags: ["wiki", "official", "agents", "skins", "patch-notes"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Agent, weapon, and map pages",
      "Skin and cosmetics catalog",
      "Patch notes and act info",
    ],
    featured: true,
  },
  {
    id: "ascend-tracker",
    name: "Ascend Tracker",
    slug: "ascend-tracker",
    shortDescription:
      "Free Riot ID lookup with rank, MMR, and match history.",
    description:
      "Ascend Tracker is a no-signup web tracker that pulls live match data from Riot’s API: rank, hidden MMR estimate, K/D, agent/map splits, and match history. A lighter alternative to Tracker.gg if you just want a fast lookup. A desktop companion is also available.",
    websiteUrl: "https://www.play-ascend.com/tracker",
    category: "Trackers & Stats",
    tags: ["stats", "no-signup", "mmr", "lookup"],
    platforms: ["web", "desktop"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Riot ID search with no account",
      "Rank and MMR estimate",
      "Match history and agent splits",
      "Optional desktop companion",
    ],
    featured: false,
  },
  {
    id: "valotracker-bot",
    name: "ValoTracker",
    slug: "valotracker",
    shortDescription:
      "Discord bot for stats lookup and automatic rank roles.",
    description:
      "ValoTracker (Valorant Stats) is a widely used Discord bot: slash-command stats for competitive and other modes, match lookup, and auto-roles for rank and region with a setup wizard. Strong pick if you run a ranked community server.",
    websiteUrl: "https://valotracker.com/",
    category: "Discord Bots & Utilities",
    tags: ["discord", "stats", "autoroles", "rank-roles"],
    platforms: ["discord"],
    pricing: "donation",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Slash-command player stats",
      "Rank and region auto-roles",
      "Match and mode breakdowns",
    ],
    safetyNotes:
      "Link accounts only through the official bot invite. Never paste a Riot password into Discord.",
    featured: false,
  },
  {
    id: "valorant-labs",
    name: "VALORANT LABS",
    slug: "valorant-labs",
    shortDescription:
      "Multilingual Discord bot for stats, MMR, news, and server status.",
    description:
      "VALORANT LABS is a Discord-verified bot used on several official regional VALORANT servers. It covers player stats, MMR by act, rank auto-roles, auto patch-notes, and cluster status. Open-source lineage; invite from the project site.",
    websiteUrl: "https://valorantlabs.xyz/",
    category: "Discord Bots & Utilities",
    tags: ["discord", "stats", "mmr", "patch-notes", "autoroles"],
    platforms: ["discord"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Player stats and MMR",
      "Auto patch notes and news",
      "Rank auto-roles",
      "Server status by cluster",
    ],
    safetyNotes:
      "Invite only from valorantlabs.xyz or the official Discord app listing.",
    featured: false,
  },
  {
    id: "valolytics",
    name: "Valolytics",
    slug: "valolytics",
    shortDescription:
      "Discord analytics bot for solo and team match review.",
    description:
      "Valolytics is a VALORANT analytics Discord bot aimed at teams and serious solo players: match tracking, map-level insights, and shareable stat cards. Built for Discord-first review rather than a public web tracker.",
    websiteUrl: "https://www.valolytics.gg/",
    category: "Discord Bots & Utilities",
    tags: ["discord", "analytics", "teams", "heatmaps"],
    platforms: ["discord"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Personal and team stats",
      "Match review in Discord",
      "Map-level insights",
    ],
    safetyNotes:
      "Team bots often need extra permissions. Review the invite scopes before adding it to a server.",
    featured: false,
  },
  {
    id: "valorantstrike",
    name: "ValorantStrike",
    slug: "valorantstrike",
    shortDescription:
      "HD skin database, collections, and featured store rotation.",
    description:
      "ValorantStrike catalogs weapon skins and collections with HD images, prices, and how-to-unlock notes. It also tracks the featured store rotation — the public bundle, not your personal four-skin shop — so no Riot login is required.",
    websiteUrl: "https://valorantstrike.com/",
    category: "Store, Inventory & Skins",
    tags: ["skins", "store", "collections", "no-login"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Skin and collection pages",
      "Featured store rotation",
      "HD images and prices",
    ],
    featured: false,
  },
  {
    id: "aimlabs",
    name: "Aimlabs",
    slug: "aimlabs",
    shortDescription:
      "Official Valorant-partnered aim trainer with map recreations.",
    description:
      "Aimlabs is the main aim trainer used by Valorant players: thousands of tasks, an AI coach, a sensitivity finder, and a Valorant Training Center with 1:1 map recreations. Free on Steam and consoles; membership unlocks extra coaching tools.",
    websiteUrl: "https://aimlabs.com/",
    category: "Other",
    tags: ["aim", "trainer", "official-partner", "practice"],
    platforms: ["desktop"],
    pricing: "freemium",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Valorant-specific training playlists",
      "Recreated maps",
      "Sensitivity finder",
      "AI coaching (paid tier)",
    ],
    featured: false,
  },
  {
    id: "mouse-sensitivity",
    name: "Mouse-Sensitivity.com",
    slug: "mouse-sensitivity",
    shortDescription:
      "Gold-standard sensitivity converter for Valorant and 1,700+ games.",
    description:
      "Mouse-Sensitivity.com is the most precise public cm/360 converter. Hipfire Valorant conversions are free; ADS and zoom aims sit behind a paid tier. Use it when moving from CS2 or another shooter and you want the same feel, not a rough eDPI guess.",
    websiteUrl: "https://www.mouse-sensitivity.com/n/valorant/",
    category: "Crosshairs & Settings",
    tags: ["sensitivity", "converter", "cm360", "edpi"],
    platforms: ["web"],
    pricing: "freemium",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Hipfire conversion across 1,700+ games",
      "eDPI, cm/360, and in/360",
      "Optional ADS / zoom conversion",
    ],
    featured: false,
  },
  {
    id: "valohunt",
    name: "ValoHunt",
    slug: "valohunt",
    shortDescription:
      "Overwolf companion that captures highlights and tracks performance.",
    description:
      "ValoHunt is a desktop Overwolf app that auto-captures matches, tracks performance, and includes ValoHunt Guessr for game-sense practice. Built for clip-and-review rather than live opponent scouting.",
    websiteUrl: "https://app.valohunt.com/",
    category: "Overlays & Desktop Apps",
    tags: ["overlay", "highlights", "clips", "overwolf"],
    platforms: ["overwolf", "desktop"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Automatic highlight capture",
      "Performance tracking",
      "ValoHunt Guessr mini-game",
    ],
    safetyNotes:
      "Overwolf overlay. Install only from Overwolf or the official ValoHunt site.",
    featured: false,
  },
  {
    id: "tricks-gg",
    name: "Tricks.gg",
    slug: "tricks-gg",
    shortDescription:
      "Lineups, agent setups, crosshairs and strategies in one place.",
    description:
      "Tricks.gg bills itself as \u201cValorant Lineups, Setups, Crosshairs, Strategies & Replay Tool\u201d. Lineups are browsable by map with step-by-step positioning, and the same site carries agent setups, crosshair codes and a replay tool \u2014 useful if you would rather not keep four tabs open.",
    websiteUrl: "https://tricks.gg",
    category: "Lineups & Strategies",
    tags: ["lineups", "setups", "strategies", "replay"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Lineups browsable by map",
      "Agent setups and strategies",
      "Crosshair codes alongside the lineups",
      "Replay tool",
    ],
    featured: false,
  },
  {
    id: "brimmate",
    name: "BrimMate",
    slug: "brimmate",
    shortDescription:
      "Interactive tactical map guides for ability lineups.",
    description:
      "BrimMate is lineup-only and map-first: pick a map and an agent, and the lineups are laid out on an interactive tactical map rather than as a video list. Covers Brimstone, Sova, Viper and Vyse across the current map pool, with community submissions.",
    websiteUrl: "https://brimmate.xyz",
    category: "Lineups & Strategies",
    tags: ["lineups", "interactive-map", "brimstone", "sova", "viper"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Interactive tactical map per lineup",
      "Brimstone, Sova, Viper and Vyse coverage",
      "Filter by map and ability",
      "Community-submitted lineups",
    ],
    featured: false,
  },
  {
    id: "ascend-crosshairs",
    name: "Ascend Crosshairs",
    slug: "ascend-crosshairs",
    shortDescription:
      "Verified VCT pro crosshair codes, refreshed every patch.",
    description:
      "Ascend\u2019s crosshair gallery lists verified codes from VCT professionals \u2014 TenZ, Aspas, Demon1, Boaster, ScreaM and others \u2014 with a live preview, one-click copy, and the source and last-updated date shown per entry. Codes are refreshed each patch, which is what separates it from the many stale pro-crosshair lists.",
    websiteUrl: "https://www.play-ascend.com/crosshairs",
    category: "Crosshairs & Settings",
    tags: ["crosshair", "pro-settings", "vct", "verified"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "154 verified VCT pro crosshairs",
      "Source and last-updated date per code",
      "Live preview before importing",
      "Team-by-team crosshair pages",
    ],
    safetyNotes:
      "The crosshair gallery is free and needs no account. The wider Ascend platform has optional paid features.",
    featured: false,
  },
  {
    id: "valdb",
    name: "VALDB",
    slug: "valdb",
    shortDescription:
      "Crosshair database and generator with pro player codes.",
    description:
      "VALDB pairs a browsable database of professional crosshair codes with a generator for building your own, plus written guides on what the individual crosshair settings actually do. Free, no account, and codes copy straight into the game.",
    websiteUrl: "https://valdb.com",
    category: "Crosshairs & Settings",
    tags: ["crosshair", "generator", "pro-settings", "guides"],
    platforms: ["web"],
    pricing: "free",
    status: "active",
    lastVerified: "2026-08-24",
    features: [
      "Pro player crosshair codes",
      "Custom crosshair generator",
      "Guides on individual crosshair settings",
      "Copy and import directly",
    ],
    featured: false,
  },
];

export function getApprovedTools(): Tool[] {
  return SEED_TOOLS;
}

export function getToolBySlug(slug: string): Tool | undefined {
  return SEED_TOOLS.find((t) => t.slug === slug);
}
